# pubspec.yaml
name: alarmapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2 # Pastikan ini kompatibel dengan Flutter SDK Anda

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  # 👇 Tambahkan dua package ini
  flutter_tts: ^4.0.0 # Untuk Text-to-Speech
  audioplayers: ^6.0.0 # Untuk memutar audio pre-recorded


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sounds/ # 👇 Tambahkan folder ini untuk audio karakter Anda
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Regular.ttf
          weight: 600